### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by morganestes** [aaronjorbin/WordPress-Theme-Directory-Slurper#4]
When running the update script, I sometimes get this warning:

```
Warning: Invalid argument supplied for foreach() in /WordPress-Theme-Directory-Slurper/update on line 63
```

That line is `foreach ( $themes as $theme ) {`; since `$themes` isn't explicitly defined as an array at this point, defining it as an empty array early on in the script "fixes" the warning. I haven't seen any negative side-effects, but I'd like a second look to see if I've missed anything. #3 has the PR.

**Comment by aaronjorbin** [comment]
Fixed by #3
