### ISSUE TITLE
Valid requests to the Themes API return 'error'

### ISSUE THREAD

**Issue by morganestes** [aaronjorbin/WordPress-Theme-Directory-Slurper#5]
Every request to the API is now returning `error`. I've tried to use cURL to rule out the `Requests` package and can't get it to work either. The same requests within WordPress work okay, but trying the request outside WP (tested with cURL and Postman) with the exact values that WP is using doesn't work.

Not sure if there's a change to the API that rejects certain requests, but I figured I'd open an issue here to keep tabs on tracking down the cause.

**Comment by GaryJones** [comment]
Are you seeing the following?

```
Determining most recent SVN revision...
Most recent SVN revision: 59491
You have not yet performed a successful sync. Settle in. This will take a while.
Updating 0211022_naranja_dos
PHP Notice:  unserialize(): Error at offset 0 of 5 bytes in /path/to/WP-Theme-Directory-Slurper/update on line 78
Unable to fetch 0211022_naranja_dos
Updating 0211027
PHP Notice:  unserialize(): Error at offset 0 of 5 bytes in /path/to/WP-Theme-Directory-Slurper/update on line 78
Unable to fetch 0211027
```

**Comment by morganestes** [comment]
Yep, that's the one.

**Comment by GaryJones** [comment]
The notice is no longer showing, but it's still not working:

![screenshot 2016-04-22 08 30 58](https://cloud.githubusercontent.com/assets/88371/14734758/909d771a-0864-11e6-8bcc-bc652f794f45.png)

**Comment by morganestes** [comment]
I updated and ran it last night, and the first few themes failed without
explanation but several worked. I haven't looked closely to see if there's
a pattern to the pass/fail themes, but I'll run it again today and see what
I can find out about the failing ones.

**Comment by aaronjorbin** [comment]
The themes that fail are themes that are in SVN, but not active in the repo.

**Comment by GaryJones** [comment]
> The themes that fail are themes that are in SVN, but not active in the repo.

Could we pass a flag to ./update, or otherwise choose to have them, or at least get a better error message (if something useful is returned from the API) to indicate that's the reason those themes are failing?

**Comment by aaronjorbin** [comment]
The api doesn't return anything useful.  

What value do you see in having those themes?

**Comment by GaryJones** [comment]
Historical reference, but not to worry.
